In [3]:
import numpy as np


arr1 = np.array([4, 2, 8, 10, 5])

print(np.mean(arr1))

5.8


In [4]:
import pandas as pd

In [8]:
scores = pd.read_csv('http://data-analytics.zybooks.com/ExamScores.csv')


In [4]:
print(scores.head())

   Exam1  Exam2  Exam3  Exam4
0    100     66     74     68
1     76     84    100     75
2     89     80    100     95
3     83     76     91     74
4     86     99     78     78


In [6]:
print(scores.mean())

Exam1    82.70
Exam2    79.40
Exam3    73.34
Exam4    76.50
dtype: float64


In [8]:
print(scores[['Exam1']].mean())

Exam1    82.7
dtype: float64


In [10]:
print(scores[['Exam1','Exam2']].mean())

Exam1    82.7
Exam2    79.4
dtype: float64


In [12]:
print(scores.median())

Exam1    83.0
Exam2    79.5
Exam3    74.5
Exam4    75.0
dtype: float64


In [14]:
print(scores[['Exam1']].median())

Exam1    83.0
dtype: float64


In [16]:
import scipy.stats as st

In [19]:
arr1 = np.array([[4, 8, 2], [2, 5, 10], [2, 1, 10]])
print (arr1)

[[ 4  8  2]
 [ 2  5 10]
 [ 2  1 10]]


In [21]:
st.mode(arr1)

ModeResult(mode=array([[ 2,  1, 10]]), count=array([[2, 1, 2]]))

In [23]:
print(scores.mode())

   Exam1  Exam2  Exam3  Exam4
0     78   84.0  100.0   74.0
1     83  100.0    NaN   75.0
2     89    NaN    NaN    NaN


In [25]:
print(scores[['Exam1']].mode())

   Exam1
0     78
1     83
2     89


In [7]:
rent = pd.read_csv('http://data-analytics.zybooks.com/rent.csv')
print(rent)

   Santa Monica CA  Boise ID  Tucson AZ  Detroit MI  Pittsburgh PA  Orlando FL
0            10230      1600       2495        3195           2480        2242
1            10000      1500       2200        2695           2435        2000
2             9000      1029       2150        2595           2405        1912
3             8500      1025       1800        2495           2350        1895
4             8250       980       1650        2495           2320        1800
5             8000       950       1600        1675           2316        1765
6             7000       950       1500        1525           2305        1685
7             6500       925       1500        1480           2290        1670
8             6000       925       1500        1410           2275        1665
9             5815       900       1500        1400           2265        1625


In [29]:
print(rent['Santa Monica CA'].mean())

7929.5


In [31]:
print(rent.mean())

Santa Monica CA    7929.5
Boise ID           1078.4
Tucson AZ          1789.5
Detroit MI         2096.5
Pittsburgh PA      2344.1
Orlando FL         1825.9
dtype: float64


In [ ]:
print(rent.median())

In [10]:
arr1 = np.array([10, 2, 5, 7, 3, 5])

In [12]:
print(np.std(arr1))

2.6246692913372707


In [15]:
print(np.var(arr1))

6.88888888888889


In [16]:
scores = pd.read_csv('http://data-analytics.zybooks.com/ExamScores.csv')

In [18]:
print(scores.std())

Exam1     9.291756
Exam2    14.332780
Exam3    21.754296
Exam4     8.056560
dtype: float64


In [20]:
print(scores[['Exam1']].std())

Exam1    9.291756
dtype: float64


In [22]:
print(scores.var())

Exam1     86.336735
Exam2    205.428571
Exam3    473.249388
Exam4     64.908163
dtype: float64


In [24]:
print(scores[['Exam1']].var())

Exam1    86.336735
dtype: float64


In [28]:
arr2 =  np.array([2,3,4,5,6,100])

In [32]:
arr2= pd.Series(arr2)
arr2.mad()

26.666666666666668